### ISSUE TITLE
Got struck and not able to run  @Dungyichao 

### ISSUE THREAD

**Issue by dineshresearch** [Dungyichao/Electric-Vehicle-Route-Planning-on-Google-Map-Reinforcement-Learning#1]
(rl) dinesh@dinesh:~/Documents/SIH/EV$ python main.py 
------------for tensorflow --------------
------------for env & google info--------------
Please help me out

**Comment by Dungyichao** [comment]
Please refer to new instruction in the Github page. New update! Thank you
