### ISSUE TITLE
AttributeError: 'environment' object has no attribute 'latt'

### ISSUE THREAD

**Issue by vikaspoonia31** [Dungyichao/Electric-Vehicle-Route-Planning-on-Google-Map-Reinforcement-Learning#2]

**Comment by Dungyichao** [comment]
Please refer to new instruction in my github page. There is some rule changed in Google map server

**Comment by vikaspoonia31** [comment]
Hi Dung,

Yes now it is working. Just needed to configure API keys according to the
new Google Maps Server.
Thanks For your help and efforts.

Best Regards,
Vikas Poonia
8010252675
