### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sbasyrine** [Dungyichao/Electric-Vehicle-Route-Planning-on-Google-Map-Reinforcement-Learning#3]
Dear Dungyichao,

Hello, I'm a reseacher who works on Electric Vehicles. In particular, I'm interested in my research on EVs that rely solely on battery energy.  I want to ask you about the problems that you faces while intergrating the charging stations along the routes and 
on what your charging and routing planning solution are based on.
Also, where can I find BEVs datasets and tutorials.
I'll be grateful if you can help me with some of your valuable advises.

cordially.

**Comment by Dungyichao** [comment]
Sorry, I didn't take the charging station into consideration

**Comment by sbasyrine** [comment]
thank you for your response. But if you have documents that helped you while navigating the map  I'll be so grateful :)

**Comment by Dungyichao** [comment]
I'm not sure what do you mean the documents. The navigating rule implemented in this project is based on the reinforcement learning concept. Please read through my Github page and then you will get most idea of the concept.

**Comment by sbasyrine** [comment]
ok thank you :)
